name: pinterest_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # connect network
  http: ^0.13.4
  http_interceptor: ^1.0.2

  # database
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  flutter_staggered_grid_view: ^0.6.2
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0

  # image
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+3
  # decoration
  lottie: ^1.3.0
  share_plus: ^4.0.10
  image_downloader: ^0.31.0
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
